### ISSUE TITLE
Error when installing via composer

### ISSUE THREAD

**Issue by SerikK** [FrenzelGmbH/cm-comments#1]
When I tried to install you extension via composer, I got next error:
Your requirements could not be resolved to an installable set of pack
                                                                     
  Problem 1                                                          
    - frenzelgmbh/cm-comments 0.0.1 requires yiisoft/yii2 2.0.* -> sa
iisoft/yii2[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2
    - frenzelgmbh/cm-comments 0.0.2 requires yiisoft/yii2 2.0.* -> sa
iisoft/yii2[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2
    - yiisoft/yii2 2.0.9 requires bower-asset/jquery.inputmask ~3.2.2
g package found.                                                     
    - yiisoft/yii2 2.0.8 requires bower-asset/jquery.inputmask ~3.2.2
g package found.                                                     
    - yiisoft/yii2 2.0.7 requires bower-asset/jquery.inputmask ~3.2.2
g package found.                                                     
    - yiisoft/yii2 2.0.6 requires bower-asset/jquery.inputmask 3.1.* 
 package found.                                                      
    - yiisoft/yii2 2.0.5 requires bower-asset/jquery.inputmask 3.1.* 
 package found.                                                      
    - yiisoft/yii2 2.0.4 requires bower-asset/jquery.inputmask 3.1.* 
 package found.                                                      
    - yiisoft/yii2 2.0.3 requires bower-asset/jquery.inputmask 3.1.* 
 package found.                                                      
    - yiisoft/yii2 2.0.2 requires bower-asset/jquery.inputmask 3.1.* 
 package found.                                                      
    - yiisoft/yii2 2.0.1 requires bower-asset/jquery.inputmask 3.1.* 
 package found.                                                      
    - yiisoft/yii2 2.0.0 requires bower-asset/jquery.inputmask 3.1.* 
 package found.                                                      
    - Installation request for frenzelgmbh/cm-comments * -> satisfiab
mbh/cm-comments[0.0.1, 0.0.2].                                       
                                                                     
Potential causes:                                                    
 - A typo in the package name                                        
 - The package is not available in a stable-enough version according 
m-stability setting                                                  
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> f
s.                                                                   
                                                                     
Read <https://getcomposer.org/doc/articles/troubleshooting.md> for fu
roblems.

**Comment by SerikK** [comment]
Sorry, my mistake... I accidentally run the command in console package

**Comment by philippfrenzel** [comment]
No worry! Hope it works;) it's kind of a very simple comment system
